spring:
  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true  
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  resources:
      static-locations: classpath:/static/,classpath:/templates/**
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
mybatis:
  type-aliases-package: com.woniuxy.oa.entity
  mapper-locations:
  - classpath:mybatis/mapper/*.xml